const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const samples={air:'Hi team, please send your best air rate from Miami to Quito. Cargo is 3 pallets, 48x40x50 each, total 1,250 lbs. Pickup is in Doral and cargo will be ready Monday. Please include pickup and AES.',ocean:'Please quote 1x40HC from Miami to Guayaquil. Commodity: furniture. Cargo ready next Wednesday. Pickup from 8400 NW 25th St, Doral. Door to port please.',local:'Need delivery tomorrow: 2 pallets, 980 lbs, from our warehouse in Doral to LATAM Cargo before 4 PM. Please use the usual trucker.'};
let activeData=null,charges=[['Air freight',1048],['Pickup',185],['Handling',95],['AES',45]],activeReplyQuote=null;
const inquiries=[{id:'IQ-0829-011',name:'ABC Imports',route:'MIA → UIO · Air',note:'3 PLT · 1,250 LB · Ready Monday',tag:'READY TO PRICE'},{id:'IQ-0829-012',name:'Finesse Decor',route:'MIA → MAD · Air',note:'Missing dimensions',tag:'NEEDS INFO'},{id:'Q-0829-008',name:'Metric Marine',route:'MIA → SJU · Air',note:'Customer replied: Please proceed',tag:'ACCEPTED'},{id:'Q-0829-006',name:'Global Tech',route:'MIA → GYE · Ocean',note:'Quote sent · waiting 19h',tag:'WAITING',wait:true}];
const quotes=[{id:'Q-0829-013',customer:'Blue Medical',route:'MIA → BOG',mode:'Air',cargo:'2 PLT · 880 LB',sell:1425,cost:1120,status:'Sent',age:'2h ago'},{id:'Q-0829-012',customer:'Global Tech',route:'MIA → GYE',mode:'Ocean',cargo:'1 × 40HC',sell:2480,cost:1960,status:'Sent',age:'19h ago'},{id:'Q-0829-008',customer:'Metric Marine',route:'MIA → SJU',mode:'Air',cargo:'1 PLT · 420 LB',sell:795,cost:610,status:'Accepted',age:'Today'}];
const jobs=[{id:'J-0829-008',quoteId:'Q-0829-008',customer:'Metric Marine',route:'MIA → SJU',mode:'Air',cargo:'1 PLT · 420 LB',sell:795,next:'Book carrier / confirm space',steps:[['Quote accepted',true],['Booking',false],['Pickup',false],['Docs',false],['Delivered',false]]}];
function money(n){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n)}
function code(v){return v==='Miami'?'MIA':v==='Quito'?'UIO':v==='Guayaquil'?'GYE':v}
function renderInbox(){inquiryList.innerHTML=inquiries.map(i=>`<div class="inquiry-item"><div class="inquiry-top"><div><strong>${i.name}</strong><p>${i.route}</p></div><span class="tag ${i.wait?'wait':''}">${i.tag}</span></div><p>${i.note}</p></div>`).join('');inboxCount.textContent=inquiries.length;needsPricingStat.textContent=inquiries.filter(x=>x.tag==='READY TO PRICE'||x.tag==='NEEDS INFO').length;waitingStat.textContent=inquiries.filter(x=>x.tag==='WAITING').length;acceptedStat.textContent=inquiries.filter(x=>x.tag==='ACCEPTED').length}
function parseRequest(text){const low=text.toLowerCase();let mode=low.includes('40hc')||low.includes('ocean')?'Ocean':low.includes('delivery')&&!low.includes('air')?'Ground':'Air';let origin=low.includes('miami')||low.includes('doral')?'Miami':'—';let destination=low.includes('quito')?'Quito':low.includes('guayaquil')?'Guayaquil':low.includes('latam cargo')?'LATAM Cargo':'—';let pieces=(text.match(/(\d+)\s*(?:pallet|plt)/i)||[])[1]||(low.includes('1x40hc')?'1 × 40HC':'—');if(pieces!=='1 × 40HC'&&pieces!=='—')pieces+=' pallets';let weight=(text.match(/([\d,]+)\s*lbs?/i)||[])[1];weight=weight?weight+' lb':'—';let dims=(text.match(/(\d+)\s*[x×]\s*(\d+)\s*[x×]\s*(\d+)/i)||[]).slice(1).join(' × ');dims=dims?dims+' in':'—';let commodity=(text.match(/commodity\s*[:\-]?\s*([^\.\n]+)/i)||[])[1]||'Not provided';let ready=low.includes('monday')?'Monday':low.includes('wednesday')?'Wednesday':low.includes('tomorrow')?'Tomorrow':'Not provided';return{customer:'ABC Imports',mode,origin,destination,pieces,weight,dims,commodity,ready,pickup:low.includes('doral')?'Doral, FL':low.includes('warehouse')?'MIP Warehouse':'Not provided',services:[low.includes('pickup')?'Pickup':null,low.includes('aes')?'AES':null].filter(Boolean).join(' + ')||'Base freight'}}
function renderSummary(d){activeData=d;const vals=[['Mode',d.mode],['Route',`${d.origin} → ${d.destination}`],['Cargo',`${d.pieces} · ${d.weight}`],['Dimensions',d.dims],['Ready',d.ready],['Pickup',d.pickup],['Commodity',d.commodity],['Included',d.services]];workspaceTitle.textContent=`${d.customer} · ${code(d.origin)} → ${code(d.destination)}`;routeLabel.textContent=`${code(d.origin)} → ${code(d.destination)}`;extractedSummary.innerHTML=vals.map(v=>`<div class="summary-item"><span>${v[0]}</span><strong>${v[1]}</strong></div>`).join('');const missing=[];if(d.commodity==='Not provided')missing.push('Commodity');if(d.dims==='—'&&d.mode==='Air')missing.push('Dimensions');if(d.destination==='—')missing.push('Destination');missingBox.className='missing-box'+(missing.length?'':' ok');missingBox.innerHTML=missing.length?`<strong>${missing.length} item${missing.length>1?'s':''} to confirm:</strong> ${missing.join(', ')}. <button class="text-btn" id="askCustomerBtn">Ask customer</button>`:'<strong>Ready to price.</strong> No blocking information detected.';const ask=$('#askCustomerBtn');if(ask)ask.onclick=()=>toast('Clarification email prepared')}
function renderCharges(){chargesEl().innerHTML=charges.map((c,i)=>`<div class="charge-row"><input value="${c[0]}" data-name="${i}"><input type="number" value="${c[1]}" data-cost="${i}"><button data-remove="${i}">×</button></div>`).join('');$$('[data-cost]').forEach(x=>x.oninput=e=>{charges[+e.target.dataset.cost][1]=+e.target.value||0;recalc()});$$('[data-name]').forEach(x=>x.oninput=e=>charges[+e.target.dataset.name][0]=e.target.value);$$('[data-remove]').forEach(x=>x.onclick=e=>{charges.splice(+e.target.dataset.remove,1);renderCharges()});recalc()}
function chargesEl(){return $('#charges')}
function recalc(){const cost=charges.reduce((a,c)=>a+(+c[1]||0),0),sell=+sellInput.value||0,profit=sell-cost,margin=sell?profit/sell*100:0;totalCost.textContent=money(cost);profitValue.textContent=money(profit);marginValue.textContent=margin.toFixed(1)+'%'}
function analyze(){const d=parseRequest(emailInput.value);renderSummary(d);charges=d.mode==='Ocean'?[['Ocean freight',1450],['Pickup',425],['Docs',85]]:d.mode==='Ground'?[['Local delivery',185]]:[['Air freight',1048],['Pickup',185],['Handling',95],['AES',45]];sellInput.value=d.mode==='Ocean'?2480:d.mode==='Ground'?285:1695;renderCharges();quoteWorkspace.classList.remove('hidden');quoteWorkspace.scrollIntoView({behavior:'smooth',block:'start'})}
function showQuote(){const d=activeData||parseRequest(emailInput.value),cost=charges.reduce((a,c)=>a+(+c[1]||0),0),sell=+sellInput.value||0;quotePreview.innerHTML=`<p>Hi,</p><p>Thank you for the opportunity. Please find our quotation below:</p><div class="customer-quote-box"><strong>${routeLabel.textContent} · ${d.mode}</strong><br>${d.pieces} · ${d.weight}<br>${d.pickup!=='Not provided'?'Pickup: '+d.pickup+'<br>':''}${d.services}<br><br><strong>Total: ${money(sell)}</strong></div><p>Rate subject to space, availability and final cargo details. Please confirm if you would like us to proceed.</p><p>Best regards,<br>MIP Cargo Express</p><small>Internal cost ${money(cost)} · not shown to customer</small>`;quoteDialog.showModal()}
function markSent(){const d=activeData||parseRequest(emailInput.value),cost=charges.reduce((a,c)=>a+(+c[1]||0),0),sell=+sellInput.value||0,id='Q-'+String(new Date().getMonth()+1).padStart(2,'0')+String(new Date().getDate()).padStart(2,'0')+'-'+String(quotes.length+14).padStart(3,'0');quotes.unshift({id,customer:d.customer,route:routeLabel.textContent,mode:d.mode,cargo:`${d.pieces} · ${d.weight}`,sell,cost,status:'Sent',age:'Just now'});inquiries.unshift({id,name:d.customer,route:`${routeLabel.textContent} · ${d.mode}`,note:`Quote ${money(sell)} sent just now`,tag:'WAITING',wait:true});quoteDialog.close();renderAll();toast(`${id} sent and added to pipeline`);switchView('quotes')}
function renderQuotes(filter='all'){const list=filter==='all'?quotes:quotes.filter(q=>q.status.toLowerCase()===filter);quotesList.innerHTML=list.map(q=>`<article class="pipeline-card"><div class="pipeline-main"><div class="quote-id">${q.id}</div><div><strong>${q.customer}</strong><p>${q.route} · ${q.mode}</p><small>${q.cargo}</small></div></div><div class="quote-finance"><span>Sell</span><strong>${money(q.sell)}</strong><small>${((q.sell-q.cost)/q.sell*100).toFixed(1)}% margin</small></div><div class="pipeline-status"><span class="status-pill ${q.status.toLowerCase()}">${q.status}</span><small>${q.age}</small></div><div class="pipeline-actions">${q.status==='Sent'?`<button class="ghost-btn reply-btn" data-reply="${q.id}">Paste reply</button>`:`<button class="primary-btn convert-btn" data-convert="${q.id}">${jobs.some(j=>j.quoteId===q.id)?'Open job':'Start job'}</button>`}</div></article>`).join('')||'<div class="empty-state">No quotes in this status.</div>';quoteCount.textContent=quotes.length;$$('.reply-btn').forEach(b=>b.onclick=()=>openReply(b.dataset.reply));$$('.convert-btn').forEach(b=>b.onclick=()=>convertToJob(b.dataset.convert))}
function openReply(id){activeReplyQuote=id;replyInput.value='Looks good. Please proceed.';replyResult.classList.add('hidden');replyDialog.showModal()}
function understandReply(){const text=replyInput.value.toLowerCase(),q=quotes.find(x=>x.id===activeReplyQuote);if(!q)return;const accepted=['proceed','approved','looks good','go ahead','confirm','accepted'].some(x=>text.includes(x));if(accepted){q.status='Accepted';q.age='Just now';replyResult.className='reply-result accepted';replyResult.innerHTML=`<strong>Accepted ✓</strong><p>Central interprets this as approval to proceed with ${q.id}.</p><button class="primary-btn" id="startJobFromReply">Start live job →</button>`;$('#startJobFromReply').onclick=()=>{replyDialog.close();convertToJob(q.id)}}else{replyResult.className='reply-result';replyResult.innerHTML='<strong>Change or clarification detected</strong><p>Keep the quote open and review the requested change before repricing.</p>';renderQuotes()}}
function convertToJob(qid){let existing=jobs.find(j=>j.quoteId===qid);if(existing){switchView('jobs');return}const q=quotes.find(x=>x.id===qid);if(!q)return;q.status='Accepted';jobs.unshift({id:'J-'+qid.slice(2),quoteId:q.id,customer:q.customer,route:q.route,mode:q.mode,cargo:q.cargo,sell:q.sell,next:q.mode==='Ocean'?'Confirm booking / sailing':'Book carrier / confirm space',steps:[['Quote accepted',true],['Booking',false],['Pickup',false],['Docs',false],['Delivered',false]]});renderAll();toast('Accepted quote converted to live job');switchView('jobs')}
function renderJobs(){jobsList.innerHTML=jobs.map(j=>`<article class="job-card"><div class="job-head"><div><span class="job-id">${j.id}</span><h3>${j.customer}</h3><p>${j.route} · ${j.mode} · ${j.cargo}</p></div><span class="status-pill accepted">LIVE</span></div><div class="next-action"><span>NEXT ACTION</span><strong>${j.next}</strong><button class="primary-btn job-next" data-job="${j.id}">Do next →</button></div><div class="step-track">${j.steps.map(s=>`<div class="step ${s[1]?'done':''}"><i>${s[1]?'✓':'○'}</i><span>${s[0]}</span></div>`).join('')}</div><div class="job-foot"><span>From ${j.quoteId}</span><strong>${money(j.sell)} sell</strong></div></article>`).join('');jobCount.textContent=jobs.length;$$('.job-next').forEach(b=>b.onclick=()=>advanceJob(b.dataset.job))}
function advanceJob(id){const j=jobs.find(x=>x.id===id),idx=j.steps.findIndex(s=>!s[1]);if(idx<0)return toast('Job already complete');j.steps[idx][1]=true;j.next=idx===1?'Arrange pickup':idx===2?'Prepare / verify documents':idx===3?'Track to delivery':idx===4?'Ready for billing':'Next operation';renderJobs();toast(`${j.steps[idx][0]} completed`)}
function renderAll(){renderInbox();renderQuotes();renderJobs()}
function switchView(name){$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===name));$$('.view').forEach(v=>v.classList.add('hidden'));$('#'+name+'View').classList.remove('hidden');const copy={inbox:['QUOTE DESK','Turn requests into quotes, fast.','Paste an email. Central extracts the move, flags what is missing, and prepares pricing.'],quotes:['QUOTE PIPELINE','Quotes that stay operational.','Track customer decisions and turn approvals directly into work.'],jobs:['OPERATIONS','Execute from the accepted quote.','No re-keying. The same commercial record continues into execution.'],records:['OPERATIONAL MEMORY','Reusable records, not repetitive forms.','Customers, vendors, lanes and rates will power the workflow.']}[name];pageEyebrow.textContent=copy[0];pageTitle.textContent=copy[1];pageSub.textContent=copy[2]}
function toast(t){const x=toastEl();x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800)}function toastEl(){return $('#toast')}
renderAll();renderCharges();
$$('.chip[data-sample]').forEach(b=>b.onclick=()=>{emailInput.value=samples[b.dataset.sample];analyze()});analyzeBtn.onclick=analyze;newInquiryBtn.onclick=()=>{switchView('inbox');emailInput.value='';quoteWorkspace.classList.add('hidden');emailInput.focus()};sellInput.oninput=recalc;addChargeBtn.onclick=()=>{charges.push(['New charge',0]);renderCharges()};prepareQuoteBtn.onclick=showQuote;closeDialog.onclick=()=>quoteDialog.close();markSentBtn.onclick=markSent;copyQuoteBtn.onclick=async()=>{try{await navigator.clipboard.writeText(quotePreview.innerText);toast('Quote email copied')}catch{toast('Copy unavailable')}};closeReplyDialog.onclick=()=>replyDialog.close();analyzeReplyBtn.onclick=understandReply;$$('.nav-item').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$$('[data-qfilter]').forEach(b=>b.onclick=()=>{$$('[data-qfilter]').forEach(x=>x.classList.remove('active-filter'));b.classList.add('active-filter');renderQuotes(b.dataset.qfilter)});