const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const samples={
 air:'Hi team, please send your best air rate from Miami to Quito. Cargo is 3 pallets, 48x40x50 each, total 1,250 lbs. Pickup is in Doral and cargo will be ready Monday. Please include pickup and AES.',
 ocean:'Please quote 1x40HC from Miami to Guayaquil. Commodity: furniture. Cargo ready next Wednesday. Pickup from 8400 NW 25th St, Doral. Door to port please.',
 local:'Need delivery tomorrow: 2 pallets, 980 lbs, from our warehouse in Doral to LATAM Cargo before 4 PM. Please use the usual trucker.'
};
const inquiries=[
 {name:'ABC Imports',route:'MIA → UIO · Air',note:'3 PLT · 1,250 LB · Ready Monday',tag:'READY TO PRICE'},
 {name:'Finesse Decor',route:'MIA → MAD · Air',note:'Missing dimensions',tag:'NEEDS INFO'},
 {name:'Metric Marine',route:'MIA → SJU · Air',note:'Customer replied: Please proceed',tag:'ACCEPTED'},
 {name:'Global Tech',route:'Miami → Guayaquil · Ocean',note:'1×40HC · Cargo ready Wed',tag:'WAITING',wait:true}
];
let charges=[['Air freight',1048],['Pickup',185],['Handling',95],['AES',45]];
function renderInbox(){const el=$('#inquiryList');el.innerHTML=inquiries.map(i=>`<div class="inquiry-item"><div class="inquiry-top"><div><strong>${i.name}</strong><p>${i.route}</p></div><span class="tag ${i.wait?'wait':''}">${i.tag}</span></div><p>${i.note}</p></div>`).join('')}
function parseRequest(text){const low=text.toLowerCase();let mode=low.includes('40hc')||low.includes('ocean')?'Ocean':low.includes('delivery')&&!low.includes('air')?'Ground':'Air';let origin=low.includes('miami')||low.includes('doral')?'Miami':'—';let destination=low.includes('quito')?'Quito':low.includes('guayaquil')?'Guayaquil':low.includes('latam cargo')?'LATAM Cargo':'—';let pieces=(text.match(/(\d+)\s*(?:pallet|plt)/i)||[])[1]|| (low.includes('1x40hc')?'1 × 40HC':'—');if(pieces!=='1 × 40HC'&&pieces!=='—')pieces+=' pallets';let weight=(text.match(/([\d,]+)\s*lbs?/i)||[])[1];if(weight)weight+=' lb';else weight='—';let dims=(text.match(/(\d+)\s*[x×]\s*(\d+)\s*[x×]\s*(\d+)/i)||[]).slice(1).join(' × ');dims=dims?dims+' in':'—';let commodity=(text.match(/commodity\s*[:\-]?\s*([^\.\n]+)/i)||[])[1]||'Not provided';let ready=low.includes('monday')?'Monday':low.includes('wednesday')?'Wednesday':low.includes('tomorrow')?'Tomorrow':'Not provided';return{customer:'ABC Imports',mode,origin,destination,pieces,weight,dims,commodity,ready,pickup:low.includes('doral')?'Doral, FL':(low.includes('warehouse')?'MIP Warehouse':'Not provided'),services:[low.includes('pickup')?'Pickup':null,low.includes('aes')?'AES':null].filter(Boolean).join(' + ')||'Base freight'}}
function renderSummary(d){const vals=[['Mode',d.mode],['Route',`${d.origin} → ${d.destination}`],['Cargo',`${d.pieces} · ${d.weight}`],['Dimensions',d.dims],['Ready',d.ready],['Pickup',d.pickup],['Commodity',d.commodity],['Included',d.services]];$('#workspaceTitle').textContent=`${d.customer} · ${d.origin==='Miami'?'MIA':d.origin} → ${d.destination==='Quito'?'UIO':d.destination==='Guayaquil'?'GYE':d.destination}`;$('#routeLabel').textContent=`${d.origin==='Miami'?'MIA':d.origin} → ${d.destination==='Quito'?'UIO':d.destination==='Guayaquil'?'GYE':d.destination}`;$('#extractedSummary').innerHTML=vals.map(v=>`<div class="summary-item"><span>${v[0]}</span><strong>${v[1]}</strong></div>`).join('');const missing=[];if(d.commodity==='Not provided')missing.push('Commodity');if(d.dims==='—'&&d.mode==='Air')missing.push('Dimensions');if(d.destination==='—')missing.push('Destination');const mb=$('#missingBox');if(missing.length){mb.className='missing-box';mb.innerHTML=`<strong>${missing.length} item${missing.length>1?'s':''} to confirm:</strong> ${missing.join(', ')}. <button class="text-btn" onclick="alert('Next: generate a customer clarification email automatically.')">Ask customer</button>`}else{mb.className='missing-box ok';mb.innerHTML='<strong>Ready to price.</strong> No blocking information detected.'}}
function renderCharges(){const box=$('#charges');box.innerHTML=charges.map((c,i)=>`<div class="charge-row"><input value="${c[0]}" data-name="${i}"><input type="number" value="${c[1]}" data-cost="${i}"><button data-remove="${i}">×</button></div>`).join('');$$('[data-cost]').forEach(x=>x.oninput=e=>{charges[+e.target.dataset.cost][1]=+e.target.value||0;recalc()});$$('[data-name]').forEach(x=>x.oninput=e=>charges[+e.target.dataset.name][0]=e.target.value);$$('[data-remove]').forEach(x=>x.onclick=e=>{charges.splice(+e.target.dataset.remove,1);renderCharges();recalc()});recalc()}
function money(n){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n)}
function recalc(){const cost=charges.reduce((a,c)=>a+(+c[1]||0),0);const sell=+$('#sellInput').value||0;const profit=sell-cost;const margin=sell?profit/sell*100:0;$('#totalCost').textContent=money(cost);$('#profitValue').textContent=money(profit);$('#marginValue').textContent=margin.toFixed(1)+'%'}
function analyze(){const d=parseRequest($('#emailInput').value);renderSummary(d);if(d.mode==='Ocean')charges=[['Ocean freight',1450],['Pickup',425],['Docs',85]];else if(d.mode==='Ground')charges=[['Local delivery',185]];else charges=[['Air freight',1048],['Pickup',185],['Handling',95],['AES',45]];renderCharges();$('#quoteWorkspace').classList.remove('hidden');$('#quoteWorkspace').scrollIntoView({behavior:'smooth',block:'start'})}
function showQuote(){const cost=charges.reduce((a,c)=>a+(+c[1]||0),0),sell=+$('#sellInput').value||0;$('#quotePreview').innerHTML=`<p>Hi,</p><p>Thank you for the opportunity. Please find our quotation below:</p><div style="background:#f7f9fc;padding:16px;border-radius:10px"><strong>${$('#routeLabel').textContent}</strong><br>Air freight service<br>3 pallets · 1,250 lb<br>Pickup included from Doral<br>AES included<br><br><strong>Total: ${money(sell)}</strong></div><p>Rate subject to space and final cargo details. Please confirm if you would like us to proceed.</p><p>Best regards,<br>MIP Cargo Express</p><small style="color:#7d8798">Internal cost ${money(cost)} · not shown to customer</small>`;$('#quoteDialog').showModal()}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800)}
renderInbox();renderCharges();
$$('.chip').forEach(b=>b.onclick=()=>{$('#emailInput').value=samples[b.dataset.sample];analyze()});$('#analyzeBtn').onclick=analyze;$('#newInquiryBtn').onclick=()=>{$('#emailInput').value='';$('#quoteWorkspace').classList.add('hidden');$('#emailInput').focus()};$('#sellInput').oninput=recalc;$('#addChargeBtn').onclick=()=>{charges.push(['New charge',0]);renderCharges()};$('#prepareQuoteBtn').onclick=showQuote;$('#closeDialog').onclick=()=>$('#quoteDialog').close();$('#markSentBtn').onclick=()=>{$('#quoteDialog').close();toast('Quote marked sent');inquiries.unshift({name:'ABC Imports',route:$('#routeLabel').textContent,note:`Quote ${money(+$('#sellInput').value||0)} sent just now`,tag:'QUOTED',wait:true});renderInbox()};$('#copyQuoteBtn').onclick=async()=>{const t=$('#quotePreview').innerText;try{await navigator.clipboard.writeText(t);toast('Quote email copied')}catch{toast('Copy unavailable')}};$$('.nav-item').forEach(b=>b.onclick=()=>{$$('.nav-item').forEach(n=>n.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.add('hidden'));$('#'+b.dataset.view+'View').classList.remove('hidden')});